---
title: "Chapter 2 Exercise"
author: "Abhishek Gupta"
date: "13/08/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggfortify)
library(fpp3)
library(fpp2)
library(tsibble)
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1
```{r}
gafa_stock
y <- gafa_stock
```
```{r}
Dummy <- gafa_stock %>%  filter(Symbol == "GOOG")
Dummy %>% autoplot(Close  - Open)
```
```{r}
A <- c()
for (val in unique(gafa_stock$Symbol))
{
  Dummy <- gafa_stock %>% filter(Symbol == val)
  Dummy_1 <- Dummy %>% filter(Close ==   max(Dummy$Close))
  A<- append(A, Dummy_1$Date)
}
print(data.frame('Symbol'=unique(gafa_stock$Symbol), 'Date with Maximum Closing'=A))

```
```{r}
autoplot(gafa_stock)
```
```{r}
PBS
```
```{r}
PBS %>% filter(ATC2 == 'A01') %>% summarise(TotalC = sum(Cost)) %>% mutate(TotalCost = TotalC/1e6) %>% autoplot(TotalCost)
```
```{r}
vic_elec
```
```{r}
vic_elec%>% autoplot()
```

```{r}
PP <- pelt %>% as_tibble(index=Year)
PP
```
```{r}
PP %>% ts.plot(gpars=list(col=rainbow(2)))
```
```{r}
PP %>%
  pivot_longer(-Year, names_to="Key", values_to="Value") %>%
  ggplot(aes(x = Year, y = Value, colour = Key)) +
    geom_line() 
```

```{r}
dim.data.frame(PP$Year)[2]
```
## Question 2

```{r}
tute1 <- readr::read_csv("tute1.csv")
View(tute1)
```

```{r}
mytimeseries <- tute1 %>%
  mutate(Quarter = yearmonth(Quarter)) %>%
  as_tsibble(index = Quarter)
mytimeseries
```
```{r}
mytimeseries %>%
  pivot_longer(-Quarter, names_to="Key", values_to="Value") %>%
  ggplot(aes(x = Quarter, y = Value, colour = Key)) +
    geom_line() +
    facet_grid(vars(Key), scales = "free_y")
```

## Question 3
```{r}

tourism_xl <- readxl::read_excel('tourism.xlsx')
tourism_xl
```
```{r}
tourism
```


```{r}
tourism_xl_ts <- tourism_xl %>% mutate(Quarter=yearquarter(Quarter)) %>% as_tibble(index=Quarter)
tourism_xl_ts
```
```{r}
tourism_grouped<-tourism_xl_ts%>%group_by(Region, Purpose)%>%summarise(AverageTrips=mean(Trips),.groups='keep')
tourism_grouped%>%filter(AverageTrips==max(tourism_grouped$AverageTrips))
```
```{r}
tourism_xl_ts%>%group_by(State)%>%summarise(TotalTrips=sum(Trips),.groups='keep')
```

## Question 4

```{r}
aus_production
```
```{r}
aus_production%>%autoplot(Bricks)
```
```{r}
pelt%>%autoplot(Lynx)
```
```{r}
gafa_stock%>%autoplot(Close)
```
```{r}
vic_elec%>%autoplot(Demand)+ggtitle('Demand Time Series Plot')+xlab('time')+ylab('Half Hourly Demand')
```

## Question 5
```{r}
aus_arrivals
```
```{r}
aus_arrivals%>%autoplot(Arrivals)
```
```{r}
aus_arrivals%>% gg_season(Arrivals)
```

```{r}
aus_arrivals%>%gg_subseries(Arrivals)
```

## Question 6
```{r}
aus_retail
```

```{r}
set.seed(1)
myseries <- aus_retail %>%
 filter(`Series ID` == sample(aus_retail$`Series ID`,1))
myseries
```

```{r}
myseries%>%autoplot(Turnover)
```
```{r}
lambda <- myseries %>%
  features(Turnover, features = guerrero) %>%
  pull(lambda_guerrero)
myseries %>% autoplot(box_cox(Turnover, lambda))
```


```{r}
myseries %>% gg_season(Turnover) 
```

```{r}
myseries %>% gg_subseries(Turnover)
```
```{r}
myseries%>%gg_lag(Turnover,geom='point')
```
```{r}
myseries%>%ACF(Turnover, lag_max=100)%>%autoplot()
```
## Question 7

```{r}
myseries <- us_employment %>%filter(Title=='Total Private')
myseries%>% autoplot(Employed)
myseries%>%gg_season(Employed)
myseries%>%gg_subseries(Employed)
myseries%>%gg_lag(Employed,geom='point')
myseries%>%ACF(Employed)%>%autoplot()
```
```{r}
myseries <- aus_production
myseries%>% autoplot(Bricks)
myseries%>%gg_season(Bricks)
myseries%>%gg_subseries(Bricks)
myseries%>%gg_lag(Bricks,geom='point')
myseries%>%ACF(Bricks)%>%autoplot()

```
```{r}
myseries <- pelt
myseries%>% autoplot(Hare)
#myseries%>%gg_season(Hare)
myseries%>%gg_subseries(Hare)
myseries%>%gg_lag(Hare,geom='point')
myseries%>%ACF(Hare)%>%autoplot()
```
```{r}
myseries <- PBS %>% filter(ATC2 == 'H02')
myseries%>% autoplot(Cost)
myseries%>%gg_season(Cost)
myseries%>%gg_subseries(Cost)
myseries%>% filter(Concession=='Concessional', Type=='Co-payments', ATC1=='H') %>%gg_lag(Cost,geom='point')
myseries%>% filter(Concession=='Concessional', Type=='Co-payments', ATC1=='H') %>% ACF(Cost) %>% autoplot()
```
```{r}
myseries <- us_gasoline
myseries%>% autoplot(Barrels)
myseries%>%gg_season(Barrels)
myseries%>%gg_subseries(Barrels)
myseries%>% gg_lag(Barrels,geom='point')
myseries%>% ACF(Barrels) %>% autoplot()
```

## Question 9
```{r}
myseries <- aus_livestock %>% filter(Animal == 'Pigs', State == 'Victoria', year(Month) >= 1990, year(Month) <= 1995)
myseries%>% autoplot(Count)
ACF_1 <- myseries%>% ACF(Count, lag_max=20)

set.seed(30)
y <- tsibble(sample = 1:100, wn = rnorm(100), index = sample)
#y %>% autoplot(wn) + ggtitle("White noise")
ACF_2 <- y %>% ACF(wn, lag_max=20)

ACF_1$acf%>% plot(type='s',col='blue', ylim = c(-0.5, 1))
ACF_2$acf%>% points(type='s',col='red')
```

## Question 10

```{r}
dgoog <- gafa_stock %>%
  filter(Symbol == "GOOG", year(Date) >= 2018) %>%
  mutate(trading_day = row_number()) %>%
  update_tsibble(index = trading_day, regular = TRUE) %>%
  mutate(diff = difference(Close))
dgoog
```

```{r}
dgoog %>% ACF(diff) %>% autoplot()
```
```{r}
recent_production <- aus_production %>%
  filter(year(Quarter) >= 1992)
recent_production %>% gg_lag(Beer,lags=1, geom="point")

plot(recent_production$Beer, lag(recent_production$Beer, 1), cex=0.7, col="blue")

lag.plot(recent_production$Beer, lags=1, type='p', do.lines=FALSE, labels=FALSE)
```
```{r}
plot(y=lag(recent_production$Beer, 1), x=recent_production$Beer)
```